"""warehouse_module

Revision ID: 844f1a9edaff
Revises: 1c45193d7657
Create Date: 2026-06-05 03:15:19.422831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '844f1a9edaff'
down_revision: Union[str, None] = '1c45193d7657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=False)
    op.create_index(op.f('ix_warehouses_type'), 'warehouses', ['type'], unique=False)
    op.create_table('inventories',
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventories_status'), 'inventories', ['status'], unique=False)
    op.create_index(op.f('ix_inventories_warehouse_id'), 'inventories', ['warehouse_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('inventory_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('counted_quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_id', 'variant_id', name='uq_inventory_item')
    )
    op.create_index(op.f('ix_inventory_items_inventory_id'), 'inventory_items', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_variant_id'), 'inventory_items', ['variant_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('from_warehouse_id', sa.Uuid(), nullable=True),
    sa.Column('to_warehouse_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('reference_type', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_actor_id'), 'stock_movements', ['actor_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_from_warehouse_id'), 'stock_movements', ['from_warehouse_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_to_warehouse_id'), 'stock_movements', ['to_warehouse_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_type'), 'stock_movements', ['type'], unique=False)
    op.create_index(op.f('ix_stock_movements_variant_id'), 'stock_movements', ['variant_id'], unique=False)
    op.create_table('stocks',
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reserved', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('min_quantity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('min_quantity >= 0', name='ck_stock_min_nonneg'),
    sa.CheckConstraint('quantity >= 0', name='ck_stock_qty_nonneg'),
    sa.CheckConstraint('reserved <= quantity', name='ck_stock_reserved_lte_qty'),
    sa.CheckConstraint('reserved >= 0', name='ck_stock_reserved_nonneg'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'variant_id', name='uq_stock_wh_variant')
    )
    op.create_index(op.f('ix_stocks_variant_id'), 'stocks', ['variant_id'], unique=False)
    op.create_index(op.f('ix_stocks_warehouse_id'), 'stocks', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_warehouse_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_variant_id'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_stock_movements_variant_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_type'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_to_warehouse_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_from_warehouse_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_actor_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_inventory_items_variant_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_inventory_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_inventories_warehouse_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_status'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_index(op.f('ix_warehouses_type'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
