"""finance_module

Revision ID: ed3249a64e76
Revises: 46eee286c0e7
Create Date: 2026-06-05 09:31:55.181170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed3249a64e76'
down_revision: Union[str, None] = '46eee286c0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'UZS'"), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('bank_name', sa.String(length=128), nullable=True),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('balance >= 0', name='ck_account_balance_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_code'), 'accounts', ['code'], unique=True)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=True)
    op.create_index(op.f('ix_accounts_type'), 'accounts', ['type'], unique=False)
    op.create_table('debt_records',
    sa.Column('party_type', sa.String(length=16), nullable=False),
    sa.Column('party_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('reference_type', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_debt_amount_positive'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_records_direction'), 'debt_records', ['direction'], unique=False)
    op.create_index(op.f('ix_debt_records_party_id'), 'debt_records', ['party_id'], unique=False)
    op.create_index(op.f('ix_debt_records_party_type'), 'debt_records', ['party_type'], unique=False)
    op.create_index(op.f('ix_debt_records_reference_id'), 'debt_records', ['reference_id'], unique=False)
    op.create_index(op.f('ix_debt_records_reference_type'), 'debt_records', ['reference_type'], unique=False)
    op.create_table('finance_payments',
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('related_account_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('reference_type', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_fp_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_payments_account_id'), 'finance_payments', ['account_id'], unique=False)
    op.create_index(op.f('ix_finance_payments_category'), 'finance_payments', ['category'], unique=False)
    op.create_index(op.f('ix_finance_payments_direction'), 'finance_payments', ['direction'], unique=False)
    op.create_index(op.f('ix_finance_payments_number'), 'finance_payments', ['number'], unique=True)
    op.create_index(op.f('ix_finance_payments_reference_id'), 'finance_payments', ['reference_id'], unique=False)
    op.create_index(op.f('ix_finance_payments_reference_type'), 'finance_payments', ['reference_type'], unique=False)
    op.create_index(op.f('ix_finance_payments_related_account_id'), 'finance_payments', ['related_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_payments_related_account_id'), table_name='finance_payments')
    op.drop_index(op.f('ix_finance_payments_reference_type'), table_name='finance_payments')
    op.drop_index(op.f('ix_finance_payments_reference_id'), table_name='finance_payments')
    op.drop_index(op.f('ix_finance_payments_number'), table_name='finance_payments')
    op.drop_index(op.f('ix_finance_payments_direction'), table_name='finance_payments')
    op.drop_index(op.f('ix_finance_payments_category'), table_name='finance_payments')
    op.drop_index(op.f('ix_finance_payments_account_id'), table_name='finance_payments')
    op.drop_table('finance_payments')
    op.drop_index(op.f('ix_debt_records_reference_type'), table_name='debt_records')
    op.drop_index(op.f('ix_debt_records_reference_id'), table_name='debt_records')
    op.drop_index(op.f('ix_debt_records_party_type'), table_name='debt_records')
    op.drop_index(op.f('ix_debt_records_party_id'), table_name='debt_records')
    op.drop_index(op.f('ix_debt_records_direction'), table_name='debt_records')
    op.drop_table('debt_records')
    op.drop_index(op.f('ix_accounts_type'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_code'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
