"""customer_module

Revision ID: 15703317ab68
Revises: 844f1a9edaff
Create Date: 2026-06-05 03:33:34.611987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '15703317ab68'
down_revision: Union[str, None] = '844f1a9edaff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_type', sa.String(length=32), nullable=True),
    sa.Column('inn', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('segment', sa.String(length=16), nullable=False),
    sa.Column('price_type', sa.String(length=16), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('current_debt', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('credit_limit >= 0', name='ck_customer_credit_limit_nonneg'),
    sa.CheckConstraint('current_debt >= 0', name='ck_customer_debt_nonneg'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_inn'), 'customers', ['inn'], unique=True)
    op.create_index(op.f('ix_customers_manager_id'), 'customers', ['manager_id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_price_type'), 'customers', ['price_type'], unique=False)
    op.create_index(op.f('ix_customers_segment'), 'customers', ['segment'], unique=False)
    op.create_table('customer_contacts',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_contacts_customer_id'), 'customer_contacts', ['customer_id'], unique=False)
    op.create_table('customer_interactions',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_interactions_actor_id'), 'customer_interactions', ['actor_id'], unique=False)
    op.create_index(op.f('ix_customer_interactions_customer_id'), 'customer_interactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_interactions_occurred_at'), 'customer_interactions', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_customer_interactions_type'), 'customer_interactions', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_interactions_type'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_occurred_at'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_customer_id'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_actor_id'), table_name='customer_interactions')
    op.drop_table('customer_interactions')
    op.drop_index(op.f('ix_customer_contacts_customer_id'), table_name='customer_contacts')
    op.drop_table('customer_contacts')
    op.drop_index(op.f('ix_customers_segment'), table_name='customers')
    op.drop_index(op.f('ix_customers_price_type'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_manager_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_inn'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
